<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\shared\ShoMark.Common\ShoMark.Common.csproj" />
    <ProjectReference Include="..\ShoMark.Services.Social.Application\ShoMark.Services.Social.Application.csproj" />
    <ProjectReference Include="..\ShoMark.Services.Social.Infrastructure\ShoMark.Services.Social.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
