<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ShoMark.Services.Campaign.Domain\ShoMark.Services.Campaign.Domain.csproj" />
    <ProjectReference Include="..\..\shared\ShoMark.Contracts\ShoMark.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\ShoMark.Messaging\ShoMark.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
